version: '3.2'
services:
  periodeec:
    image: wichtf/periodeec
    container_name: periodeec
    environment:
    - DEEMIX_URL=<http://your_deemix_url:6595>
    - DEEZER_EMAIL=<deezer email>
    - DEEZER_PASSWORD=<deezer password>
    - SPOTIFY_USERNAMES=<a list of spotify username from which you want to download playlists>
    - SPOTIFY_CLIENT_ID=<spotify client id>
    - SPOTIFY_CLIENT_SECRET=<spotify client secret>
    - INTERVAL=<interval to run the script in seconds>